// Import the session context used to access and update session data
import { useSession } from "../../Context/SessionContext";

// Import the presentational components displayed inside the side panel
import SessionInfo from "./SessionInfo";
import ScenariosPanel from "./ScenariosPanel";
import InfoCard from "./InfoCard";

/*
  SidePanel consumes SessionContext.
  It acts as the "Smart Container" following the Braude architecture.
*/

function SidePanel() {
  // Get the session data, request state, and status update function
  const { sessionInfo, loading, error, updateSessionStatus } = useSession();

  // Display a loading message while the session data is being retrieved
  if (loading) {
    return (
      <aside className="w-full space-y-4">
        <InfoCard title="Session" value="Loading..." />
      </aside>
    );
  }

  // Display an error message when the session data cannot be loaded
  if (error || !sessionInfo) {
    return (
      <aside className="w-full space-y-4">
        <InfoCard title="Error" value="Session data unavailable" />
      </aside>
    );
  }

  // --- TIMER LOGIC HOUSED IN THE SMART COMPONENT ---

  // Handle reminder messages generated by the session timer
  function handleTimerReminder(message) {
    // We will hook this up to your chat log later!
    console.log("System Reminder:", message);
  }

  // Mark the session as completed when the available time ends
  function handleTimeUp() {
    console.log("Time is up! Transitioning session status.");

    // This will force the App.jsx to render the PostTaskSurvey
    if (updateSessionStatus) {
      updateSessionStatus("completed");
    }
  }

  return (
    <aside className="flex w-full flex-col gap-4 lg:gap-6">
      {/* Pass the logic down as props to the presentational component */}
      <SessionInfo
        sessionInfo={sessionInfo}
        onTimeUp={handleTimeUp}
        onReminder={handleTimerReminder}
      />

      {/* Background story + scenarios, revealed gradually over the session */}
      <ScenariosPanel />
    </aside>
  );
}

// Export the component for use in other files
export default SidePanel;
