// Import the Mongoose library for defining and working with MongoDB models
const mongoose = require("mongoose");

// Define the structure of a learning session document
const sessionSchema = new mongoose.Schema(
  {
    // Reference to the student who owns the session
    studentId: {
      // Store the ID of a document from the User collection
      type: mongoose.Schema.Types.ObjectId,

      // Connect this field to the User model
      ref: "User",

      // Require every session to belong to a student
      required: true,
    },

    // Reference to the chat connected to the session
    chatId: {
      // Store the ID of a document from the Chat collection
      type: mongoose.Schema.Types.ObjectId,

      // Connect this field to the Chat model
      ref: "Chat",

      // Use null until a chat is created and connected to the session
      default: null,
    },

    // Store the research group assigned to the student
    group: {
      // The group value must be a string
      type: String,

      // Allow only the experimental group or control group
      enum: ["Experimental Group", "Control Group"],

      // Require every session to have an assigned group
      required: true,
    },

    // Store the student's current learning layer
    currentLayer: {
      // The layer value must be a string
      type: String,

      // Allow only the four defined learning layers
      enum: ["Broad Context", "Structure", "Dynamics", "Evaluation"],

      // Start every new session at the Broad Context layer
      default: "Broad Context",
    },

    // Store the number of hints used during the session
    hintsUsed: {
      // The hint counter must be a number
      type: Number,

      // Start the hint counter at zero
      default: 0,
    },

    // Store the names of the requirements already completed by the student
    unlockedGates: {
      // Store the unlocked gates as an array of strings
      type: [String],

      // Start with an empty array because no gates are initially unlocked
      default: [],
    },

    // Store the amount of time remaining in the session
    remainingTime: {
      // The remaining time is stored as a string
      type: String,

      // Start every new session with twenty minutes
      default: "20:00",
    },

    // Store the current state of the session
    status: {
      // The session status must be a string
      type: String,

      // Allow only active, completed, or paused as status values
      enum: ["active", "completed", "paused"],

      // Mark every new session as active
      default: "active",
    },

    // Store recent questions generated by the bot
    lastBotQuestions: {
      // Store the bot questions as an array of strings
      type: [String],

      // Start with an empty array because no bot questions exist initially
      default: [],
},
  },
  {
    // Automatically create createdAt and updatedAt fields
    timestamps: true,
  }
);

// Create and export the Session model using the defined schema
module.exports = mongoose.model("Session", sessionSchema);